export const products = [
    {
      id: 0,
      name: "Rosewood Serenity",
      price: 75,
      scent: "Woody",
      description: "A luxurious blend of rosewood and amber, exuding elegance and warmth. Perfect for evening occasions.",
      size: "100ml",
      qte: 0,
      promotion: true,
      image: "/assets/floral.jpg",
      stock:5,
    },
    {
      id: 1,
      name: "Citrus Blossom",
      price: 50,
      scent: "floral",
      description: "A fresh burst of citrus with hints of orange and lemon, perfect for summer days.",
      size: "50ml",
      qte: 0,
      promotion: false,
      image: "/assets/floral2.jpg",
      stock:5,
    },
    {
      id: 2,
      name: "Vanilla Dream",
      price: 65,
      scent: "fruity",
      description: "A sweet and comforting aroma of vanilla bean, ideal for cozy evenings.",
      size: "100ml",
      qte: 0,
      promotion: true,
      image: "/assets/fruity.jpg",
      stock:5,
    },
    {
      id: 3,
      name: "Ocean Breeze",
      price: 60,
      scent: "fruity",
      description: "A refreshing marine fragrance that evokes the feeling of a gentle ocean breeze.",
      size: "75ml",
      qte: 0,
      promotion: false,
      image: "/assets/woody.jpg",
      stock:5,
    },
    {
      id: 4,
      name: "Spiced Oud",
      price: 90,
      scent: "floral",
      description: "An exotic blend of oud and spices for a bold and captivating presence.",
      size: "100ml",
      qte: 0,
      promotion: true,
      image: "/assets/floral4.jpg",
      stock:5,
    },
  ];
